### ISSUE TITLE
__call__() got an unexpected keyword argument 'last_change'

### ISSUE THREAD

**Issue by ThomasCr** [mknx/smarthome#141]
mit dem aktuellen develop bekomme ich folgenden Fehler und keine Temperaturen mehr angezeigt.

```
2014-12-23 01:57:09,008 DEBUG    Main         KNX: eg.kueche.temperature.set listen on 4/3/130 -- __init__.py:parse_item:243
2014-12-23 01:57:09,056 DEBUG    Main         Item eg.kueche.temperature.set = 20.0 via SQLite None None -- item.py:set:472
2014-12-23 01:57:09,057 DEBUG    Main         KNX: eg.kueche.temperature.state listen on 4/1/130 -- __init__.py:parse_item:243
2014-12-23 01:57:09,105 DEBUG    Main         Item eg.kueche.temperature.state = 68.2 via SQLite None None -- item.py:set:472
2014-12-23 01:57:09,105 DEBUG    Main         KNX: Temperatur reply to 4/2/130 -- __init__.py:parse_item:275
2014-12-23 01:57:09,155 ERROR    Main         Item eg.kueche.temperature: problem creating: __call__() got an unexpected keyword argument 'last_change' -- item.py:__init__:221
Traceback (most recent call last):
  File "/usr/local/smarthome.new/lib/item.py", line 219, in __init__
    child = Item(smarthome, self, child_path, value)
  File "/usr/local/smarthome.new/lib/item.py", line 275, in __init__
    update = plugin.parse_item(self)
  File "/usr/local/smarthome.new/plugins/sqlite/__init__.py", line 144, in parse_item
    item.set(value, 'SQLite', prev_change=prev_change, last_change=last_change)
TypeError: __call__() got an unexpected keyword argument 'last_change'
```
Eine Idee ob es am Code liegt oder an der SQL DB (die beim ersten starten nach dem update ebenfalls upgedatet wurde).

Gruß

**Comment by ohinckel** [comment]
Der Parameter last_change wurde der Item Klasse hinzugefügt, zum nahezu gleichen Zeitpunkt auch das Sqlite Plugin erweitert (26./27.01.2014). Ich habe die History und die Commits nicht alle durchgeschaut und kann daher nichts genaueres dazu sagen.

Der Fall tritt auch nur dann auf, wenn die Sqlite DB einen cache-Eintrag und einen historisierten Wert hat. D.h. es müsste beim nächsten Neustart wieder auftreten, sofern der Wert geändert wurde und dadurch einen History-Eintrag erzeugt wurde.

Vielleicht liegt es auch an dem Software-Stand, den du verwendest. Vermutlich develop, aber welche Revision?

**Comment by ThomasCr** [comment]
Das Problem ist bei mir nicht mehr aufgetreten, kann wohl deswegen auch geschlossenen werden.

**Comment by ohinckel** [comment]
> Das Problem ist bei mir nicht mehr aufgetreten, kann wohl deswegen auch geschlossenen werden.

Zur Info: Vermutlich verwendest du keine Item mit dem Namen `set` mehr. Das ueberschreibt naemlich aktuell die `set()` Methode des `dict` mit der `__call__()` Methode der `Item` Klasse (siehe dazu auch referenziertes Issue).
